suankularb-wittayalai-school/mysk-frontend

- package-lock.json
- package.json
- src/utils/supabaseClient.ts
**Features**
- Add supabase client file for connecting with supabase
> Supabase Setup

- src/components/ContactChip.tsx
- src/components/dialogs/EditPerson.tsx
- src/components/home-sections/UserSection.tsx
- src/pages/account/login.tsx
- src/pages/s/[classID]/class.tsx
- src/pages/s/home.tsx
- src/pages/t/admin/students.tsx
- src/pages/t/admin/teachers.tsx
- src/pages/t/home.tsx
- src/utils/types/contact.ts
- src/utils/types/person.ts
**Features**
- Login now use account from supabase
- Logout now actually remove the session
- Home page for both student and teacher now show actual data from supabase
**Fixes**
- add `contacts` to a person type
> Authentication

- src/components/dialogs/EditPerson.tsx
- src/pages/s/home.tsx
- src/pages/t/admin/index.tsx
- src/pages/t/admin/students.tsx
- src/pages/t/admin/teachers.tsx
- src/pages/t/home.tsx
- src/utils/backend/contact/index.ts
- src/utils/backend/database.ts
- src/utils/backend/person/person.ts
- src/utils/backend/person/student.ts
- src/utils/backend/person/teacher.ts
- src/utils/hooks/auth.ts
- src/utils/types/database/contact.ts
- src/utils/types/database/person.ts
- src/utils/types/database/subject.ts
- src/utils/types/person.ts
**Features**
- Admin Panel now fetch from database
- Default Contact is added once the person is created
**Fixes**
- add types that are from database
- add function that translate database types to frontend type
- helper function to create student and teacher
- delete student or teacher now delete the person
> Refactor: types translator

- src/components/Layout.tsx
- src/pages/api/account/student.ts
- src/pages/api/account/teacher.ts
- src/pages/index.tsx
- src/pages/s/home.tsx
- src/pages/t/admin/classes.tsx
- src/pages/t/admin/index.tsx
- src/pages/t/admin/students.tsx
- src/pages/t/admin/subjects.tsx
- src/pages/t/admin/teachers.tsx
- src/pages/t/home.tsx
- src/utils/backend/person/teacher.ts
- src/utils/hooks/auth.ts
**Features**
- Nav bar now render based from role of the user
- `useSession` handle role base redirect if needed
**Fixes**
- `useStudentAccount` and `useTeacherAccount` now return a session along with the user object
> Permission and Admin

- src/components/dialogs/EditClass.tsx
- src/components/tables/ClassTable.tsx
- src/pages/t/admin/classes.tsx
- src/utils/backend/classroom/classroom.ts
- src/utils/backend/contact/index.ts
**Features**
- Edit Dialog now work for Classes
> Class Editing

- src/components/dialogs/ConnectSubject.tsx
- src/pages/t/subjects/[subjectID].tsx
- src/utils/backend/database.ts
- src/utils/types/database/subject.ts
**Features**
- Connecting Class to a subject
- Editing a room subject
- Deleting a room subject
**Fixes**
- Class and class advisor for both student and teacher are now fetched from the database
> Subject Detail page

- src/pages/news/form/[formID].tsx
- src/utils/backend/news/form.ts
- src/utils/backend/person/person.ts
- src/utils/types/database/news.ts
**Features**
- Form Submission now save to database
> Form Submission

- public/static/locales/en-US/common.json
- public/static/locales/th/common.json
- src/components/news/NewsPageWrapper.tsx
- src/pages/news/form/[formID].tsx
**Fixes**
- Dropdown visual on page load doesn’t reflect internal data
- News Banner has too much padding on mobile
> Hotfix: Dropdown Default

- next-i18next.config.js
- package-lock.json
- package.json
- src/middleware.ts
- src/pages/index.tsx
- src/pages/s/[classNumber]/schedule.tsx
- src/pages/s/[classNumber]/teachers.tsx
- src/utils/backend/classroom/classroom.ts
- src/utils/backend/news/info.ts
**Fixes**
- Landing fails to load on in-site navigation
- Student Schedule is stuck in an infinite loading loop
> Fix: Landing Fetch

- package-lock.json
- package.json
- src/pages/_app.tsx
- src/pages/t/admin/schedule/[grade].tsx
- src/utils/backend/schedule/schedule.ts
**Features**
- Admin Schedule Lookup
- Cursor indicated loading during page transition
> Admin Schedule

- src/utils/backend/classroom/classroom.ts
- src/utils/backend/database.ts
- src/utils/types/database/class.ts
**Features**
- Class Number is now fetchable from the database and supported to be shown
**Fixes**
- Student class number is supported
Fixes #52
> Class Number

- public/static/locales/en-US/class.json
- src/components/Layout.tsx
- src/middleware.ts
- src/utils/backend/person/student.ts
- src/utils/backend/person/teacher.ts
- src/utils/hooks/auth.ts
**Fixes**
- Navigation should route with user data in mind
Fixes #79
- Wrong capitalization of a title in Manage Class
**Notes to QA**
Test this PR by observing the effect the account logged has on Navigation
> Fix: Navigation should route with user data in mind

- src/pages/welcome.tsx
> Hotfix citizen id validation

- src/pages/welcome.tsx
- src/utils/backend/person/person.ts
**Features**
- Allow the teacher to set this year's advisory data
Resolves #92
**Notes for QA**
To test the PR, use a known retired or quit teacher account to log in and test the feature. Please comment on which class you used to test so we can remove the teacher from said class accordingly.
> Advisor Setup for Teacher

- src/components/dialogs/AddClass.tsx
- src/components/dialogs/AddSubject.tsx
- src/pages/account/index.tsx
- src/pages/class/[classNumber]/manage.tsx
- src/pages/index.tsx
- src/pages/welcome.tsx
- src/utils/helpers/loading.ts
**Features**
- `withLoading` helper function
**Fixes**
- An empty Landing Feed still shows
- Welcome sometimes redirect back to Welcome
- Add Subject internal default mismatches with the visual
- Teachers can add multiple instances of the same class to a subject
- Class Chip List in Add Subject has unpredictable behavior
- Add Class sometimes pass on the class from the last time the dialog is used
- Add Class allows submit even when fetching and conversion of the class is not complete
- Search is not fully stretched horizontally on mobile in Manage Class
> Fix: Issues found by Taradol

- package-lock.json
- package.json
- src/middleware.ts
**Fixes**
- Welcome redirects back to Welcome
> Migration: use `auth-helpers-nextjs` in middleware

- src/components/ContactChip.tsx
- src/pages/class/[classNumber]/manage.tsx
- src/utils/backend/classroom/classroom.ts
- src/utils/backend/contact/index.ts
- src/utils/backend/database.ts
- src/utils/backend/person/person.ts
**Fixes**
- Teacher advisory being mandatory
Fixes #114 
- Navbar reset to default
Fixes #117 
- Add contact fail and not delectable
Fixes #118 
Fixes #119
> Fix: Teacher related issues

- public/static/locales/en-US/landing.json
- src/pages/welcome.tsx
**Fixes**
- Remove lot number and administering center from welcome in vaccine section
> Vaccine properties correction

- src/components/dialogs/ConnectSubject.tsx
- src/pages/welcome.tsx
**Features**
- Animations for Vaccine Data Section
**Fixes**
- Dropdown in Vaccine Card is partially hidden
- Classes ending in “10” is erroneously treated as invalid in Connect Subject Dialog
> Animations for Vaccine Data Section

- src/components/HoverList.tsx
- src/components/schedule/SubjectPeriod.tsx
- src/pages/welcome.tsx
- src/styles/global.css
- src/utils/helpers/schedule.ts
- src/utils/helpers/validators.ts
**Fixes**
- Some passports are not validated correctly
Fixes #131
- Long teacher name split into many lines in Schedule Period
Fixes #132
- The Schedule Period in session should be highlighted, but is not
> Side note: the fix was that an array index starts at 0, not 1.
> Fix: Welcome Fields and Period

- src/pages/welcome.tsx
**Fixes**
- General Information not allowing submit
> Hotfix: citizen ID validation impossible to fulfill

- components/account/ContactSection.tsx
- components/account/RequestForgorDialog.tsx
- components/lookup/person/ShareDialog.tsx
- components/schedule/AddPeriodDialog.tsx
- pages/index.tsx
- utils/backend/schedule/utils.ts
**Features**
- Vercel Custom Events
**Fixes**
- `isOverlappingExistingItems` ignores year and semester
- A Schedule Item with many rooms is not allowed
- Redirect from Magic Link does not continue to redirect to Learn/Teach
> Beta Release 0.4.1 (Hotfix)

- components/class/ClassStudents.tsx
- components/class/ClassTeachers.tsx
- components/class/PrintStudentList.tsx
- components/common/print/PaperPreview.tsx
- components/common/print/PrintPage.tsx
- components/icons/SchemeIcon.tsx
- components/lookup/class/ClassTabs.tsx
- components/lookup/person/ShareDialog.tsx
- pages/lookup/person/index.tsx
- utils/backend/person/student.ts
- utils/helpers/contact.ts
**Features**
- Save VCards of all Students in a Class
- Immediately switch Class Tabs instead of waiting for the load to finish to increase perceived responsiveness
**Fixes**
- Print Page partially turns into a different color when horizontally scrolled
- The detail side of Class Teachers and Lookup People never stops loading
> [0.5.0] Save Class VCards

- .prettierrc.json
- components/schedule/GlanceCountdown.tsx
- components/schedule/ScheduleAtAGlance.tsx
- pages/learn.tsx
- pages/teach.tsx
- public/static/locales/en-US/schedule.json
- public/static/locales/th/schedule.json
- utils/helpers/date.ts
- utils/helpers/schedule.ts
**Features**
- Schedule at a Glance banner
- `getTodaySetToPeriodTime` helper
**Fixes**
- Added TailwindCSS class rearranger to the Prettier plugin list
> [0.6.0] Schedule at a Glance

- utils/backend/person/getStudentsByIDs.ts
**Fixes**
- Students mix-up in Student List Printout
> Fix: Students Mix-up in Student List Printout

- components/Layout.tsx
- components/classes/ClassDetailsCard.tsx
- components/classes/ClassHeader.tsx
- components/classes/GradeSection.tsx
- components/classes/LookupClassCard.tsx
- components/home/HomeGlance.tsx
- components/lookup/people/PersonHeader.tsx
- middleware.ts
- pages/classes/index.tsx
- pages/learn.tsx
- pages/manage/index.tsx
- pages/teach.tsx
- public/static/locales/en-US/common.json
- public/static/locales/th/common.json
- utils/backend/classroom/getLookupClassrooms.ts
- utils/backend/schedule/getRelevantPeriodOfClass.ts
- utils/helpers/permitted.ts
- utils/helpers/schedule/getCurrentPeriod.ts
- utils/helpers/within.ts
**Features**
- Manage in Navigation Bar/Rail/Drawer
Previously there was no way to access Manage for a non-management Person with permission
- Admins can now see Attendance and Student List of every Classroom in the Classes page
**Fixes**
- Relevant Period in Classes rely on the server being on the same timezone as the client
- Home pages now all share the same Page Header: ”MySK“
- The Assembly and Homeroom variants of Home Glance are missing the link to Attendance
> [0.8.1] Home Issues

- components/attendance/ClassAttendanceLayout.tsx
- pages/manage/attendance/date/[date].tsx
**Fixes**
- Summary is not side-by-side when printed
- Reduced impact of when Chrome fails to recognize print theme
**Notes**
Try printing [Friday’s summary](https://pr.mysk.school/manage/attendance/date/2023-12-08).
> [0.8.1] Fix: Printable Attendance on Chrome

- utils/backend/attendance/recordAttendances.ts
- utils/helpers/attendance/useAttendanceActions.ts
**Fixes**
- Date Attendance page always report success when saving even if an error occurred
- Upsert sometimes fail while saving in Date Attendance page, switched to delete-then-insert approach instead to remedy this
> Beta Release 0.8.2 (Hotfix)

- components/account/certificates/CertificateCard.tsx
- utils/backend/certificate/getCertificatesOfPerson.ts
- utils/backend/person/getStudentByID.ts
- utils/backend/person/getStudentsByIDs.ts
- utils/types/certificate.ts
- utils/types/supabase.ts
**Features**
- Certificate receiving order
> Beta Release 0.8.10

- components/attendance/AttendanceBulkActions.tsx
- components/attendance/AttendanceDatePickerDialog.tsx
- components/attendance/AttendanceFigure.tsx
- components/attendance/AttendanceFigureDay.tsx
- components/attendance/AttendanceFigureEvent.tsx
- components/attendance/HomeroomContentDialog.tsx
- components/attendance/HomeroomContentEditor.tsx
- components/attendance/MonthAttendanceLegend.tsx
- components/attendance/MonthAttendanceSummary.tsx
- components/attendance/MonthBarSparkline.tsx
- components/attendance/MonthStudentCard.tsx
- components/attendance/TodaySummary.tsx
- pages/classes/[classNumber]/attendance/date/[date].tsx
- pages/classes/[classNumber]/attendance/month/[date].tsx
- pages/manage/index.tsx
- public/static/locales/en-US/attendance.json
- public/static/locales/th/attendance.json
- utils/backend/attendance/getMonthAttendanceOfClass.ts
- utils/helpers/attendance/getAttendanceSummary.ts
- utils/helpers/getISODateString.ts
- utils/patterns.ts
**Features**
- Month Attendance page
- Added native validation to Attendance Date Picker Dialog
(Supported browsers now gray out future dates)
**Fixes**
- `YYYYMMRegex` rejects October
> [0.9.0] Month Attendance Page

- components/home/sake/SakeCelebration.tsx
**Fixes**
- Surprise on mobile
**Notes**
Preview available at https://pr.mysk.school/.
> [0.9.1] Surprise on Mobile

- components/common/PersonAvatar.tsx
- components/elective/ChooseButton.tsx
- components/elective/CreateOfferDialog.tsx
- components/elective/IncomingTradeOfferCard.tsx
- components/elective/ManageTradesCard.tsx
- components/elective/OutgoingTradeOfferCard.tsx
- components/elective/TradeOfferCard.tsx
- components/elective/TradeOfferParticipant.tsx
- components/elective/TradesCardHeader.tsx
- components/elective/TradesCardSection.tsx
- pages/learn/elective.tsx
- public/static/locales/en-US/elective.json
- public/static/locales/th/elective.json
- utils/backend/mysk/useMySKClient.ts
- utils/backend/person/getPersonByID.ts
- utils/backend/person/getStudentByID.ts
- utils/backend/person/getStudentsByIDs.ts
- utils/backend/person/getTeacherByID.ts
- utils/types/person.ts
- Incoming Trade Offer Card
Resolves FRO-79 [(link)](https://linear.app/skiso/issue/FRO-79/incoming-trade-card)
Resolves FRO-5
- Cool swap animation
- Matched loading Outgoing Trade Offer Card style to that of Incoming Trade Offer Card
- Added more error handling and analytics to Learn Electives page
- `useMySKClient` fetches way too many times
- Elective Trade Offer fetches return nothing if user is both sending and receiving Offers
- `profile_url` support to handle MySK API inconsistency
- Renamed Create Offer Dialog
This is the current main feature PR. Preview available at https://pr.mysk.school/.
> [0.10.0] Incoming Trade Offers

- components/classes/ClassDetailsCard.tsx
- Added more permission checks for viewing and editing Contacts of Classrooms
Fixes FRO-112 [(link)](https://linear.app/skiso/issue/FRO-112/add-more-permission-checks-on-classroom-contacts)
This is not a main version PR. Preview not available.
> Beta Release 0.9.5 (Hotfix)

- components/classes/StudentListPrintout.tsx
- components/classes/StudentListTableBody.tsx
- components/classes/StudentsPrintOptions.tsx
- public/static/locales/en-US/classes.json
- public/static/locales/th/classes.json
- Added extra options in Student List Printout
Resolves FRO-99 [(link)](https://linear.app/skiso/issue/FRO-99/elective-options-in-student-list-printout)
- Added filtering options for students with allergies and students without elective subjects
Resolves FRO-88
- Hidden chosen elective column from students 
Resolves FRO-86
> [0.10.0] Elective Options In Student List Printout

- .gitignore
- components/elective/ElectiveListItem.tsx
- pages/learn/elective.tsx
- pages/teach/elective.tsx
- styles/global.css
- Modified Elective List Item to support admin interface
Resolves FRO-83 [(link)](https://linear.app/skiso/issue/FRO-83/modify-elective-list-item-to-support-admin-interface)
- Added `desktop.ini` to `.gitignore`
- Fade-out utility classes
This is the current main feature PR. Preview available at https://pr.mysk.school/.
> [0.10.0] Elective List Item for Teachers

- components/classes/ClassDetailsCard.tsx
- Students cannot view Classroom Contacts at all
Fixes FRO-122 [(link)](https://linear.app/skiso/issue/FRO-122/students-cannot-view-classroom-contacts-at-all)
This is not a main version PR. Preview not available.
> Beta Release 0.9.6 (Hotfix)

- components/elective/ElectiveDetailsCard.tsx
- components/elective/ElectiveStudentList.tsx
- components/elective/ElectiveStudentListCard.tsx
- pages/_document.tsx
- pages/manage/electives/index.tsx
- pages/teach/electives/index.tsx
- public/static/locales/en-US/elective.json
- public/static/locales/th/elective.json
<div align="center">
</div>
- Enrolled Students in Elective Details Dialog
Resolves FRO-135 [(link)](https://linear.app/skiso/issue/FRO-135/enrolled-students-in-elective-details-dialog)
- Extracted Elective Student List component out of Elective Student List Card
- Bottommost Elective List Item obscured by Navigation Bar on mobile
- Cannot select the last selected Elective List Item in Teach Electives on mobile
Preview available at https://pr2.mysk.school/.
> [0.10.3] Enrolled Students in Elective Details

- components/elective/ElectiveDetailsCard.tsx
<div align="center">
</div>
- Print Chip in Elective Details Dialog
Resolves FRO-141 [(link)](https://linear.app/skiso/issue/FRO-141/print-chip-in-elective-details-dialog)
Preview available at https://pr1.mysk.school/.
> [0.10.3] Print Chip in Elective Details Dialog

- pages/learn/electives.tsx
- Enrolled Elective ignores academic year and semester
Fixes FRO-142 [(link)](https://linear.app/skiso/issue/FRO-142/enrolled-elective-ignores-academic-year-and-semester)
Preview available at https://preview.mysk.school/.
> Beta Release 0.10.3 (Hotfix)

- components/classes/ClassStudentList.tsx
- components/classes/StudentListTableBody.tsx
- pages/classes/[classNumber]/print.tsx
- pages/manage/electives/print.tsx
- utils/backend/person/getStudentByID.ts
- utils/backend/person/getStudentsByIDs.ts
- utils/backend/person/getStudentsForBulkPrint.ts
- `includeChosenElective` option in `getStudentByID` and `getStudentsByIDs`
- Bulk print pages return not found
Fixes FRO-143 [(link)](https://linear.app/skiso/issue/FRO-143/bulk-print-pages-return-not-found)
- Every Student in Classroom List Printout shown as randomized
Fixes FRO-144
- `getStudentByID` and `getStudentsByIDs` ignores academic year and semester when fetching for chosen Elective(s)
Preview available at https://pr1.mysk.school/.
> [0.10.4] Fix: Bulk Print Pages Error

- pages/404.tsx
- pages/classes/[classNumber]/attendance/date/[date].tsx
- pages/manage/classrooms/print.tsx
- 404 error pages tracking
Resolves FRO-152 [(link)](https://linear.app/skiso/issue/FRO-152/404-error-pages-tracking)
- Moved Date Attendance to SSR
Fixes FRO-148
- Parent URL of `/manage/classrooms/print` should be `/manage`
Fixes FRO-149
Preview available at https://pr1.mysk.school/.
> [0.10.5] 404 Pages Tracking

- components/attendance/AttendanceDatePickerDialog.tsx
- components/attendance/SchoolWideAttendanceTable.tsx
- pages/classes/[classNumber]/attendance/date/[date].tsx
- pages/manage/attendance/[date].tsx
- public/static/locales/en-US/manage.json
- public/static/locales/th/manage.json
- utils/backend/attendance/getClassroomAttendances.ts
- utils/helpers/attendance/isValidAttendanceDate.ts
- utils/types/attendance.ts
- COVID-19 count in Attendance Overview
Resolves FRO-174 [(link)](https://linear.app/skiso/issue/FRO-174/covid-absence-type-selection)
- New columns and sparkline design in School-wide Attendance Table
- New chart summary design in Attendance Overview
- Date Attendance for today is not available until 07:00
Fixes FRO-175
- Test Classrooms are now hidden from School-wide Attendance Table
Preview available at https://preview.mysk.school/.
> Beta Release 0.10.8 (Hotfix)

- components/classes/ClassDetailsCard.tsx
- components/classes/GradeSection.tsx
- components/classes/LookupClassCard.tsx
- components/elective/ElectiveDetailsCard.tsx
- components/elective/ElectiveLayout.tsx
- components/lookup/LookupDetailsDialog.tsx
- components/lookup/LookupDetailsSide.tsx
- components/lookup/document/DocumentDetailsCard.tsx
- components/lookup/document/LookupDocumentCard.tsx
- components/lookup/people/PersonHeader.tsx
- components/lookup/students/LookupStudentCard.tsx
- components/lookup/students/StudentDetailsCard.tsx
- components/lookup/teachers/LookupTeacherCard.tsx
- components/lookup/teachers/TeacherDetailsCard.tsx
- components/person/WithPersonDetails.tsx
- i18n.js
- pages/_app.tsx
- pages/classes/index.tsx
- pages/learn/electives.tsx
- pages/manage/electives/index.tsx
- pages/search/documents/results.tsx
- pages/search/students/results.tsx
- pages/search/teachers/results.tsx
- pages/teach/electives/index.tsx
- utils/helpers/search/useListDetail.ts
- utils/helpers/useBreakpoint.ts
- `useBreakpoint` hook
- `Breakpoint` enum
- `useListDetail` hook
- Classes
- Learn/Teach/Manage Electives
- Search Students/Teachers/Documents
- The header part Document Details Card has the wrong color
Preview available at https://pr1.mysk.school/.
> [0.11.0] Refactor: List-detail Hook

- components/elective/ElectiveListItem.tsx
- pages/classes/[classNumber]/attendance/month/[date].tsx
- pages/learn/electives.tsx
- public/static/locales/en-US/elective.json
- public/static/locales/th/elective.json
- Disable the previously selected subject from last semester.
Resolves [FRO-208](https://linear.app/skiso/issue/FRO-209/disable-subject-previously-selected-on-semester-1)
Preview available at https://mysk-git-feat-0111disable-previous-b0958c-suankularb-developers.vercel.app/.
> Beta Release 0.11.1

- .gitignore
- pages/learn/electives.tsx
**Fixes**
- Electives subjects showing all subjects in database without check for current semester subjects.
> [0.11.2] Only Filter Current Semester Subjects (Hotfix)

- .gitignore
- pages/learn/electives.tsx
**Fixes**
- Electives subjects showing all subjects in database without check for current semester subjects.
> Beta Release 0.11.2 (Hotfix)

- components/attendance/AbsenceTypeSelector.tsx
- utils/helpers/attendance/tallyAttendances.ts
- utils/patterns.ts
- Make activity leave shown as absent but counted as present
> [0.12.0] Changes to Activity Leave

- utils/helpers/attendance/isValidAttendanceDate.ts
- utils/helpers/lastWeekday.ts
**Features**
- Added special attendance day using an environment variable
> [0.12.1] Add Special Attendance Day

- pages/teach/report/index.tsx
- Nonfunctional report list filter
> [0.12.3] Teaching Report (Hotfix)

- components/account/certificates/CertificatesYearSection.tsx
- Allow receiving order number and seat code to be shown independently
> Beta Release 0.12.6 (Second Hotfix)
